import React,{useEffect,useState}from"react";
import {View,Text,TextInput,Pressable,StyleSheet,Alert,ActivityIndicator}from"react-native";
import {useRouter}from"expo-router";
import * as Linking from"expo-linking";
import {supabase}from"../lib/supabase";
import {C}from"../constants/theme";
export default function ResetPassword(){
 const router=useRouter();const[ready,setReady]=useState(false);const[password,setPassword]=useState("");const[confirm,setConfirm]=useState("");const[busy,setBusy]=useState(false);
 useEffect(()=>{let mounted=true;(async()=>{try{const url=await Linking.getInitialURL();if(!supabase)throw new Error("SUPABASE_UNAVAILABLE");if(url){const parsed=Linking.parse(url);const code=typeof parsed.queryParams?.code==="string"?parsed.queryParams.code:null;if(code){const {error}=await supabase.auth.exchangeCodeForSession(code);if(error)throw error;}}const {data,error}=await supabase.auth.getSession();if(error||!data.session)throw new Error("LINK_INVALID");if(mounted)setReady(true)}catch{if(mounted){Alert.alert("Link expirado","Solicite uma nova recuperação de senha.");router.replace("/auth")}}})();const sub=Linking.addEventListener("url",async({url})=>{try{if(!supabase)throw new Error("SUPABASE_UNAVAILABLE");const parsed=Linking.parse(url);const code=typeof parsed.queryParams?.code==="string"?parsed.queryParams.code:null;if(code){const {error}=await supabase.auth.exchangeCodeForSession(code);if(error)throw error;const {data}=await supabase.auth.getSession();if(!data.session)throw new Error("LINK_INVALID");setReady(true)}}catch{Alert.alert("Link inválido","Solicite uma nova recuperação de senha.");router.replace("/auth")}});return()=>{mounted=false;sub.remove()}},[]);
 async function save(){if(password.length<8)return Alert.alert("Senha","Use pelo menos 8 caracteres.");if(password!==confirm)return Alert.alert("Senha","As senhas não coincidem.");if(!supabase)return Alert.alert("Configuração","O BORA não conseguiu conectar ao servidor.");setBusy(true);const {error}=await supabase.auth.updateUser({password});setBusy(false);if(error)return Alert.alert("Não foi possível alterar",error.message);Alert.alert("Senha atualizada","Sua senha foi alterada com sucesso.");router.replace("/");}
 if(!ready)return <View style={s.center}><ActivityIndicator color={C.gold}/><Text style={s.muted}>Validando seu link...</Text></View>;
 return <View style={s.wrap}><Text style={s.logo}>BORA</Text><Text style={s.title}>Criar nova senha</Text><Text style={s.muted}>Escolha uma senha nova para continuar.</Text><TextInput value={password} onChangeText={setPassword} secureTextEntry placeholder="Nova senha" placeholderTextColor={C.muted} style={s.input}/><TextInput value={confirm} onChangeText={setConfirm} secureTextEntry placeholder="Confirme a nova senha" placeholderTextColor={C.muted} style={s.input}/><Pressable style={s.cta} disabled={busy} onPress={save}><Text style={s.ctaText}>{busy?"SALVANDO...":"ATUALIZAR SENHA"}</Text></Pressable></View>
}
const s=StyleSheet.create({center:{flex:1,backgroundColor:C.bg,alignItems:"center",justifyContent:"center",gap:10},wrap:{flex:1,backgroundColor:C.bg,padding:22,paddingTop:100},logo:{color:C.gold,fontSize:45,fontWeight:"900",fontStyle:"italic"},title:{color:C.text,fontSize:24,fontWeight:"900",marginTop:35},muted:{color:C.muted,fontSize:10,marginTop:7},input:{marginTop:16,backgroundColor:C.card,borderWidth:1,borderColor:C.line,borderRadius:14,padding:15,color:C.text,fontSize:14},cta:{height:52,borderRadius:15,backgroundColor:C.gold,alignItems:"center",justifyContent:"center",marginTop:18},ctaText:{color:"#071018",fontWeight:"900"}});